In [1]:
#  pip install numpy
import numpy as np

In [3]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros([5, 7, 8, ])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [12]:
np.zeros((5, 7, 8, ))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(4,20) # [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(-12, 1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [23]:
arreglo_pares = np.arange(0, 20, 2) 

In [28]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [36]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [35]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [41]:
np.arange(24).reshape(6,4).reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [39]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [42]:
# suma
a + b

array([15, 15, 15])

In [43]:
# resta
a - b

array([5, 5, 5])

In [45]:
# multiplicacion
a * b

array([50, 50, 50])

In [44]:
# divisiones
a / b

array([2., 2., 2.])

In [46]:
# Mod
a % b

array([0, 0, 0], dtype=int32)

In [52]:
# Multiplicar
print(a * 10)
# Sumar
print(a + 7)
# Restar
print(a - 2)
# Restar
print(a / 2)
# Mod
print(a % 3)

[100 100 100]
[17 17 17]
[8 8 8]
[5. 5. 5.]
[1 1 1]


In [53]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [55]:
resp = arreglo_muestra > 5

In [59]:
resp

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [ ]:
arreglo_muestra[resp]

In [60]:
arreglo_muestra[(arreglo_muestra>5) * (arreglo_muestra<12) * (arreglo_muestra%2==0)]

array([ 6,  8, 10])

In [63]:
resp_mayor_cinco = arreglo_muestra > 5
arreglo_muestra[resp_mayor_cinco]
resp_menor_doce = arreglo_muestra < 12
arreglo_muestra[resp_menor_doce]
arreglo_muestra[resp_mayor_cinco & resp_menor_doce]

array([ 6,  7,  8,  9, 10, 11])

In [65]:
resp = (arreglo_muestra > 5) & (arreglo_muestra < 12)
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11])

In [70]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [71]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [72]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [73]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [74]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [77]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
arreglo_doce.sum()

66

In [79]:
arreglo_doce.min()

0

In [80]:
arreglo_doce.max()

11

In [85]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [86]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [87]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [88]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])